### ISSUE TITLE
Configure Active Job for background jobs

### ISSUE THREAD

**Issue by rocketnova** [navapbc/template-application-rails#13]
Configure Active Job to be able to run tasks in the background.

References:
* https://guides.rubyonrails.org/v7.1/active_job_basics.html

**Comment by ellery-nava** [comment]
@rocketnova - not familiar with any of these backends. Does Nava have a preferred one? 
Is there a sample job we want to configure, or is this a matter of selecting a backend and setting it as part of the application?

**Comment by rocketnova** [comment]
@ellery-nava I think we could split this ticket into separate tickets:

1. This ticket: configure Active Job to use the in-memory rails built in queuing system. This demonstrates the queuing functionality.
2. Separate ticket: spike to identify the queuing system we recommend by default and write up an ADR as the final result. I know @kyeah has flagged that there are [licensing fee considerations for sidekiq](https://sidekiq.org/), so it may not be the right choice for us, even if it's one of the simplest to set up. 
    1. Possible follow-on separate ticket: Implement the queuing system. This might involve setting up a separately deployable microservice.

From the [rails guide](https://guides.rubyonrails.org/v7.1/active_job_basics.html#backends):

> Rails itself only provides an in-process queuing system, which only keeps the jobs in RAM. If the process crashes or the machine is reset, then all outstanding jobs are lost with the default async backend. This may be fine for smaller apps or non-critical jobs, but most production apps will need to pick a persistent backend.

**Comment by ellery-nava** [comment]
@rocketnova - I'm sure this is my unfamiliarity with Rails, but what does it mean to configure Active Job if we're not selecting a queuing system in the application config? From reading the docs, they go through generating a sample job (which it seems will run with the built-in queuing system if not otherwise specified). Does this ticket involve generating a sample job for something like sending email, so that a Nava engineer using this as a template has an example to build off of? Otherwise it seems like Active Job is integrated enough that we wouldn't necessarily need extra config to just use the built-in system.

**Comment by ellery-nava** [comment]
@rocketnova - makes sense! just took a look and I do see an issue for the starter kit to set up background jobs, so it doesn't look like anything extra needs to be captured there

**Comment by ellery-nava** [comment]
New ticket here: https://github.com/navapbc/template-application-rails/issues/25
